### PR TITLE
null check

### LINKED ISSUE #146: Segmentation fault when trying to edit buffer
Hello,

i get:
 [1] 137328 segmentation fault (core dumped)  ../bin/SHADERed
when I "create buffer" and then try to edit that same buffer.

### PR DESCRIPTION
**Pull request by branc116**
Fixes #146 

I tested this code and it looks like it works when I try to run it.
What do you think?

BTB!

### CODE REVIEW

**Comment by branc116** [comment]
What I wanted to say is: When I build SHADERed with this fix, I can "create buffer" and I can edit that same buffer and I don't get seg fault.

**Comment by dfranx** [comment]
Thanks for the PR! Tested & merged!

**Comment by branc116** [comment]
I made a video where I demonstrate the bug [here](https://youtu.be/LIPALB6r4uQ?t=315). Only about 30 secs of the video are dedicated to showing the bug. Rest of the video is on croatian so it's probably not important to you.

**Comment by branc116** [comment]
Cool, np. Gr8 tool btw.

**Comment by dfranx** [comment]
I watched all 4 videos of your SHADERed videos.

Few small tips:
- you can double click on the pipeline item to open the text editor
- you can "detach" an UI window by grabbing it by the title and then dragging it, this way you can dock the windows however you want to (so that you don't have to resize them like this):
image

- logs are turned off by default, you can turn on the logs at the end of the `Options` -> `General` page

BTW your UI scale seems too big (or font size), not sure if intentional, but if it's not intentional you can change it in `Windows` -> `Options` -> `General` if you want to

Also, to debug shaders, go to `Window` -> `Options` -> `Preview` and turn on the `statusbar` option. You'll be able to pause the preview with a button (or you can just click the space key).
Once the preview is paused, just left click on a pixel and stuff will popup in the pixel inspect window.
To debug a compute shader, right click on it in the pipeline window -> `Debug` -> enter thread ID.

**Comment by branc116** [comment]
Thanks for the tips.
Also, the situation with drivers is interesting. On my laptop I have dedicated and integrated gpu. I guess they use different drivers:
* When I've forced SHADERed to use dedicated gpu, 2/3 times I didn't get a seg fault.
* When I've forced SHADERed to use integrated gpu, it'd seg fault every time.

I also looked at reference page for [``glGetBufferSubData``](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetBufferSubData.xhtml) and didn't find anything under which conditions call to this function would seg fault.
I guess enumerating conditions for seg fault is out of scope for khronos reference and I guess your assumption is correct that it depends on driver implementation.

**Pull request merged**
