### PR TITLE
basic dds file loading, 3d tex support

### PR DESCRIPTION
**Pull request by jandy123**
Had to do lots of additional modifications to get it compiled on linux.

The real modifications start really with src/SHADERed/GUIManager.cpp below.

Hope this helps better than my patch ;).

### CODE REVIEW

**Comment by dfranx** [comment]
So I've just seen that this is ported from some NVIDIA SDK, not sure what license it uses, wouldn't want to get in trouble.

I'll postpone this feature for some other update, have to think about the implementation too, not sure if maybe rather than having Texture3D and Image3D object there's only one, Image3D. But anyway..

Thank you so much for opening the pull request!

**Comment by jandy123** [comment]
The current attempt uses Image3D. It's just some additional functions to trigger loading the texture file.
===
So, if the license is the only issue, I could look a bit more for some alternative format with some proper license and supporting library and will get back to it.

**Comment by jandy123** [comment]
Btw. please find here 

https://github.com/paroj/nv_dds/issues/1

some discussion regarding nv_dds. This should clear things up, right ?

Thanks !

**Comment by dfranx** [comment]
Implemented using my own MIT licensed .dds loader.

**Pull request closed without merging**
